In [2]:
import sys, time, timeit, cProfile, pstats, importlib, os, math, scipy
sys.path.insert(0,'/home/uq/apps/muq2inst/lib')

import matplotlib.pyplot as plt
import matplotlib.cm as cm
import numpy as np

from IPython.display import display, HTML
display(HTML("<style>.container { width:100% !important; }</style>"))
import matplotlib
%matplotlib notebook
%matplotlib inline
matplotlib.rcParams['figure.figsize'] = (40., 7.)
matplotlib.rcParams.update({'font.size': 22})

import numpy as np
import itertools as it
from numpy.polynomial.legendre import legvander

from Database import *
from Densities import *
from MultiIndex import *
from Surrogates import *
from Transport import *

import plotutil, randutil, lejautil, legendreutil

In [7]:
m = TotalDegreeSet(dim=2, order=2)

points = lejautil.leja_points(m)
lhs = legendreutil.evaluate_basis(points, m)
G = np.dot(lhs.T, lhs)#/m.size() - np.eye(m.size())
print(G)
np.linalg.norm(G, ord=2)

[[ 1.5         0.4330127   2.51557647  0.4330127   0.          2.51557647]
 [ 0.4330127   3.75        0.96824584  0.          0.         -0.48412292]
 [ 2.51557647  0.96824584  6.5625     -0.48412292  0.          3.75      ]
 [ 0.4330127   0.         -0.48412292  3.75        0.          0.96824584]
 [ 0.          0.          0.          0.          9.          0.        ]
 [ 2.51557647 -0.48412292  3.75        0.96824584  0.          6.5625    ]]


11.624902443329283